/**
 * @generated
 *
 * AUTOGENERATED. DO NOT EDIT! 
 *
 */

#import <Foundation/Foundation.h>
#import "IFServiceClient.h"
#import "gittypes.h"


@interface git: IFServiceClient
- (GitPublicUser*)userWithUserName:(NSString*)userName
	andError:(NSError* __autoreleasing*)error;
- (NSArray*)reposWithUserName:(NSString*)userName
	andError:(NSError* __autoreleasing*)error;
@end

