/**
 * @generated
 *
 * AUTOGENERATED. DO NOT EDIT! 
 *
 */

#import <Foundation/Foundation.h>
#import "IFServiceClient.h"

@interface GitUser: NSObject
- (instancetype)initWithLogin:(NSString*)login
	andTheId:(int64_t)theId
	andAvatarUrl:(NSString*)avatarUrl
	andName:(NSString*)name;
- (instancetype)initWithDictionary:(NSDictionary*)dictionary error:(NSError* __autoreleasing*)error;
- (instancetype)initWithJSONData:(NSData*)jsonData error:(NSError* __autoreleasing*)error;
- (NSDictionary*)dictionaryWithError:(NSError* __autoreleasing*)error;
- (NSData*)dumpWithError:(NSError* __autoreleasing*)error;
@property (nonatomic) NSString* login;
@property (nonatomic) int64_t theId;
@property (nonatomic) NSString* avatarUrl;
@property (nonatomic) NSString* name;
@end

@interface GitPublicUser: GitUser
- (instancetype)initWithLogin:(NSString*)login
	andTheId:(int64_t)theId
	andAvatarUrl:(NSString*)avatarUrl
	andName:(NSString*)name
	andEmail:(NSString*)email
	andPublicRepos:(int32_t)publicRepos
	andFollowers:(int32_t)followers
	andFollowing:(int32_t)following;
- (instancetype)initWithDictionary:(NSDictionary*)dictionary error:(NSError* __autoreleasing*)error;
- (instancetype)initWithJSONData:(NSData*)jsonData error:(NSError* __autoreleasing*)error;
- (NSDictionary*)dictionaryWithError:(NSError* __autoreleasing*)error;
- (NSData*)dumpWithError:(NSError* __autoreleasing*)error;
@property (nonatomic) NSString* email;
@property (nonatomic) int32_t publicRepos;
@property (nonatomic) int32_t followers;
@property (nonatomic) int32_t following;
@end

@interface GitRepo: NSObject
- (instancetype)initWithTheId:(int32_t)theId
	andName:(NSString*)name
	andOwner:(GitUser*)owner
	andTheDescription:(NSString*)theDescription
	andUrl:(NSString*)url
	andForks:(int32_t)forks
	andOpenIssues:(int32_t)openIssues
	andWatchers:(int32_t)watchers;
- (instancetype)initWithDictionary:(NSDictionary*)dictionary error:(NSError* __autoreleasing*)error;
- (instancetype)initWithJSONData:(NSData*)jsonData error:(NSError* __autoreleasing*)error;
- (NSDictionary*)dictionaryWithError:(NSError* __autoreleasing*)error;
- (NSData*)dumpWithError:(NSError* __autoreleasing*)error;
@property (nonatomic) int32_t theId;
@property (nonatomic) NSString* name;
@property (nonatomic) GitUser* owner;
@property (nonatomic) NSString* theDescription;
@property (nonatomic) NSString* url;
@property (nonatomic) int32_t forks;
@property (nonatomic) int32_t openIssues;
@property (nonatomic) int32_t watchers;
@end


