/**
 * @generated
 *
 * AUTOGENERATED. DO NOT EDIT! 
 *
 */


#import <Foundation/Foundation.h>
#import "IFTransport.h"

@interface OBCBusinessModelRevisionsItem: NSObject
- (NSDictionary*)dictionaryWithError:(NSError* __autoreleasing*)error;
- (NSData*)dumpWithError:(NSError* __autoreleasing*)error;
- (instancetype)initWithVersion:(int32_t)version
	andModel:(OBCBusinessModel*)model;
- (instancetype)initWithDictionary:(NSDictionary*)dictionary error:(NSError* __autoreleasing*)error;
- (instancetype)initWithJSONData:(NSData*)jsonData error:(NSError* __autoreleasing*)error;
@property (nonatomic) int32_t version;
@property (nonatomic) OBCBusinessModel* model;
@end;

@interface OBCBusinessModel: NSObject
- (NSDictionary*)dictionaryWithError:(NSError* __autoreleasing*)error;
- (NSData*)dumpWithError:(NSError* __autoreleasing*)error;
- (instancetype)initWithName:(NSString*)name
	andRevisions:(NSArray*)revisions
	andTheDescription:(NSString*)theDescription;
- (instancetype)initWithDictionary:(NSDictionary*)dictionary error:(NSError* __autoreleasing*)error;
- (instancetype)initWithJSONData:(NSData*)jsonData error:(NSError* __autoreleasing*)error;
@property (nonatomic) NSString* name;
@property (nonatomic) NSArray*/*OBCBusinessModelRevisionsItem*/ revisions;
@property (nonatomic) NSString* theDescription;
@end;
